version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/project/Collabdiraies
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_pm2.sh
      timeout: 300
      runas: root
